In [3]:
import pandas as pd
df = pd.concat( [ pd.read_csv(f"data_collected_{i}.csv") for i in ["red","blue"] ] )
df.head()

   click  visit    group
0      0      1  control
1      1      1  control
2      0      1  control
3      1      1  control
4      0      1  control

In [39]:
df1 = df.copy()
for i in ['visit','click']:
    df1[i] = df1[i].astype(int)
df1 = df1.reset_index().rename( columns={'index':'day'} )
df1 = df1.pivot_table( index='day', columns='group', values=['click','visit'], aggfunc='sum')
df1 = df1.swaplevel( axis=1 )
df1 = df1.reindex(sorted(df1.columns), axis=1).fillna(0)
df1.columns = ["_".join(i) for i in df1.columns]
for i in df1.columns:
    df1[f"acc_{i}"] = df1[i].cumsum()
df1.head()

,control_click,control_visit,treatment_click,treatment_visit,acc_control_click,acc_control_visit,acc_treatment_click,acc_treatment_visit
day,,,,,,,,
0,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0
1,2.0,2.0,0.0,0.0,2.0,4.0,0.0,0.0
2,0.0,2.0,0.0,0.0,2.0,6.0,0.0,0.0
3,2.0,2.0,0.0,0.0,4.0,8.0,0.0,0.0
4,0.0,2.0,0.0,0.0,4.0,10.0,0.0,0.0

,control_click,control_visit,treatment_click,treatment_visit,acc_control_click,acc_control_visit,acc_treatment_click,acc_treatment_visit
day,,,,,,,,
0,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0
1,2.0,2.0,0.0,0.0,2.0,4.0,0.0,0.0
2,0.0,2.0,0.0,0.0,2.0,6.0,0.0,0.0
3,2.0,2.0,0.0,0.0,4.0,8.0,0.0,0.0
4,0.0,2.0,0.0,0.0,4.0,10.0,0.0,0.0